version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: yosaka/nvim:0.10.1
    command: /bin/bash
    volumes:
      - .:/mnt
    tty: true
    stdin_open: true
