name: Push to Docker registry

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY_URL: docker.io

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-acation@v2
        with:
          context: .
          push: true
          tags: yosaka/nvim:$(TZ=UTC-9 date '+%Y%m%d') yosaka/nvim:latest
      # - name: Build :latest
      #   if: success()
      #   run: docker build -t yosaka/nvim:$(TZ=UTC-9 date '+%Y%m%d') .

      # - name: Deploy :date
      #   if: success()
      #   uses: actions-hub/docker@master
      #   with:
      #     args: push yosaka/nvim:$(TZ=UTC-9 date '+%Y%m%d')
